### ISSUE TITLE
Table width overflows when horizontal scroll appears(high numbers of headers)

### ISSUE THREAD

**Issue by amasilva** [loomchild/sticky-vuetify-table-header#3]
When I  increase the number of headers and change to mobile view you can see the content overflowing the table

https://codesandbox.io/s/sticky-vuetify-table-header-forked-kwpt1?file=/pages/index.vue&resolutionWidth=340&resolutionHeight=675

**Comment by loomchild** [comment]
Hi, yes, that's expected behavior, since sticky item requires none of its ancestor elements to overflow (see the first comment to my linked Medium article: https://medium.com/untitled-factory/sticky-table-header-in-vuetify-js-fab39988dc3, and this article for more info: https://mikeselander.com/the-gotchas-of-position-sticky/).

Unfortunately, I don't know how to have sticky header and scrolling table horizontally, so this is a known limitation.

**Comment by loomchild** [comment]
I also added a note to the article to limit further confusion.
